# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       libpthread-stubs

# >> macros
# << macros

Summary:    PThread Stubs for XCB
Version:    0.4
Release:    1
Group:      System/X11
License:    MIT
URL:        http://xcb.freedesktop.org
Source0:    http://xcb.freedesktop.org/dist/libpthread-stubs-%{version}.tar.bz2
Source1:    libpthread-stubs-rpmlintrc
Source100:  libpthread-stubs.yaml

%description
This library provides weak aliases for pthread functions not provided in libc
or otherwise available by default


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post


# << install post

%files
%defattr(-,root,root,-)
# >> files
%{_libdir}/pkgconfig/pthread-stubs.pc
# << files
